name: tdd_practice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^8.0.3
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  assets:
    - .env